//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XUnitTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GdaxConfigResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GdaxConfigResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XUnitTest.GdaxConfigResource", typeof(GdaxConfigResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;id&quot;: &quot;71452118-efc7-4cc4-8780-a5e22d4baa53&quot;,
        ///        &quot;currency&quot;: &quot;BTC&quot;,
        ///        &quot;balance&quot;: &quot;0.0000000000000000&quot;,
        ///        &quot;available&quot;: &quot;0.0000000000000000&quot;,
        ///        &quot;hold&quot;: &quot;0.0000000000000000&quot;,
        ///        &quot;profile_id&quot;: &quot;75da88c5-05bf-4f54-bc85-5c775bd68254&quot;
        ///    },
        ///    {
        ///        &quot;id&quot;: &quot;e316cb9a-0808-4fd7-8914-97829c1925de&quot;,
        ///        &quot;currency&quot;: &quot;USD&quot;,
        ///        &quot;balance&quot;: &quot;80.2301373066930000&quot;,
        ///        &quot;available&quot;: &quot;79.2266348066930000&quot;,
        ///        &quot;hold&quot;: &quot;1.0035025000000000&quot;,
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccountsJson {
            get {
                return ResourceManager.GetString("AccountsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Key&quot;:&quot;key&quot;,&quot;Secret&quot;:&quot;secret&quot;,&quot;passphrase&quot;:&quot;passphrase&quot;}.
        /// </summary>
        internal static string ConfigJson {
            get {
                return ResourceManager.GetString("ConfigJson", resourceCulture);
            }
        }
    }
}
